import { auth } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";
import Link from "next/link";

import AppShell from "@/components/AppShell";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";

export default async function DashboardPage() {
  const { userId } = await auth();

  if (!userId) redirect("/");

  const clients = await prisma.client.findMany({
    where: { userId },
    include: { sessions: true },
    orderBy: { createdAt: "desc" },
  });

  const totalClients = clients.length;

  const totalSessions = clients.reduce(
    (total: number, client: any) => total + client.sessions.length,
    0
  );

  const recentSessions = clients
    .flatMap((client: any) =>
      client.sessions.map((session: any) => ({
        ...session,
        clientName: client.name,
        clientId: client.id,
      }))
    )
    .sort(
      (a: any, b: any) =>
        new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
    )
    .slice(0, 4);

  return (
    <AppShell>
      <section className="rounded-3xl border bg-white p-8 shadow-sm">
        <p className="text-sm font-semibold text-violet-600">Dashboard</p>

        <h1 className="mt-3 max-w-3xl text-4xl font-bold tracking-tight text-slate-950 md:text-5xl">
          ✨ AI Client Notes & Follow-Up Generator
        </h1>

        <p className="mt-4 max-w-2xl text-slate-600">
          Save time, stay organised, and turn rough client notes into summaries,
          action points, and follow-up messages.
        </p>

        <div className="mt-6 flex flex-wrap gap-3">
          <Link
            href="/clients"
            className="rounded-xl bg-violet-600 px-5 py-3 text-sm font-semibold text-white shadow-sm hover:bg-violet-700"
          >
            View Clients
          </Link>

          <Link
            href="/clients/new"
            className="rounded-xl border bg-white px-5 py-3 text-sm font-semibold text-slate-700 hover:bg-slate-50"
          >
            Add New Client
          </Link>
        </div>
      </section>

      <section className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <div className="rounded-2xl border bg-white p-6 shadow-sm">
          <p className="text-sm text-slate-500">Clients</p>
          <p className="mt-3 text-3xl font-bold text-slate-950">
            {totalClients}
          </p>
          <p className="mt-2 text-xs text-emerald-600">Active workspace</p>
        </div>

        <div className="rounded-2xl border bg-white p-6 shadow-sm">
          <p className="text-sm text-slate-500">Sessions</p>
          <p className="mt-3 text-3xl font-bold text-slate-950">
            {totalSessions}
          </p>
          <p className="mt-2 text-xs text-emerald-600">Session notes saved</p>
        </div>

        <div className="rounded-2xl border bg-white p-6 shadow-sm">
          <p className="text-sm text-slate-500">Follow-Ups</p>
          <p className="mt-3 text-3xl font-bold text-slate-950">
            {totalSessions}
          </p>
          <p className="mt-2 text-xs text-emerald-600">Generated by AI</p>
        </div>

        <div className="rounded-2xl border bg-white p-6 shadow-sm">
          <p className="text-sm text-slate-500">Time Saved</p>
          <p className="mt-3 text-3xl font-bold text-slate-950">
            {totalSessions * 10}m
          </p>
          <p className="mt-2 text-xs text-emerald-600">Estimated</p>
        </div>
      </section>

      <section className="mt-6 grid gap-6 xl:grid-cols-2">
        <div className="rounded-2xl border bg-white p-6 shadow-sm">
          <div className="mb-5 flex items-center justify-between">
            <h2 className="text-xl font-bold text-slate-950">
              Recent Session Notes
            </h2>

            <Link
              href="/clients"
              className="text-sm font-medium text-violet-600 hover:text-violet-700"
            >
              View all
            </Link>
          </div>

          {recentSessions.length === 0 ? (
            <div className="rounded-xl border border-dashed p-6 text-slate-500">
              No sessions yet. Add a client session to see it here.
            </div>
          ) : (
            <div className="space-y-3">
              {recentSessions.map((session: any) => (
                <Link
                  key={session.id}
                  href={`/clients/${session.clientId}`}
                  className="flex items-center justify-between rounded-xl border p-4 hover:bg-slate-50"
                >
                  <div>
                    <p className="font-semibold text-slate-900">
                      {session.clientName}
                    </p>
                    <p className="mt-1 line-clamp-1 text-sm text-slate-500">
                      {session.content}
                    </p>
                  </div>

                  <span className="rounded-full bg-violet-50 px-3 py-1 text-xs font-medium text-violet-700">
                    Summary generated
                  </span>
                </Link>
              ))}
            </div>
          )}
        </div>

        <div className="rounded-2xl border bg-white p-6 shadow-sm">
          <div className="mb-5 flex items-center justify-between">
            <h2 className="text-xl font-bold text-slate-950">
              Follow-Up Queue
            </h2>

            <Link
              href="/clients"
              className="text-sm font-medium text-violet-600 hover:text-violet-700"
            >
              Review
            </Link>
          </div>

          {recentSessions.length === 0 ? (
            <div className="rounded-xl border border-dashed p-6 text-slate-500">
              No follow-ups generated yet.
            </div>
          ) : (
            <div className="space-y-3">
              {recentSessions.map((session: any) => (
                <Link
                  key={session.id}
                  href={`/clients/${session.clientId}`}
                  className="flex items-center justify-between rounded-xl border p-4 hover:bg-slate-50"
                >
                  <div>
                    <p className="font-semibold text-slate-900">
                      {session.clientName}
                    </p>
                    <p className="mt-1 text-sm text-slate-500">
                      Follow-up message ready
                    </p>
                  </div>

                  <span className="rounded-full bg-slate-100 px-3 py-1 text-xs text-slate-600">
                    Ready
                  </span>
                </Link>
              ))}
            </div>
          )}
        </div>
      </section>
    </AppShell>
  );
}